# Generated by Django 3.2.6 on 2021-08-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='raceinfo',
            name='horces',
            field=models.ManyToManyField(related_name='horces', to='collect.HorseInfo'),
        ),
    ]
