# Generated by Django 3.2.6 on 2021-08-14 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0003_auto_20210815_0423'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlaceInfo',
            new_name='CourseInfo',
        ),
        migrations.RenameField(
            model_name='raceinfo',
            old_name='place',
            new_name='course',
        ),
    ]
