# Generated by Django 3.2.6 on 2021-08-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0004_auto_20210815_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='name',
            field=models.CharField(choices=[('Sapporo', '札幌'), ('Hakodate', '函館'), ('Sapporo', '福島'), ('Sapporo', '新潟'), ('Sapporo', '東京'), ('Sapporo', '中山'), ('Sapporo', '中京'), ('Sapporo', '京都'), ('Sapporo', '阪神'), ('Sapporo', '小倉')], max_length=32, unique=True),
        ),
    ]
