# Generated by Django 3.2.6 on 2021-08-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0005_alter_courseinfo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='name',
            field=models.CharField(choices=[('Sapporo', '札幌'), ('Hakodate', '函館'), ('Fukushima', '福島'), ('Nigata', '新潟'), ('Tokyo', '東京'), ('Nakayama', '中山'), ('Chukyo', '中京'), ('Kyoto', '京都'), ('Hanshin', '阪神'), ('Ogura', '小倉')], max_length=32, unique=True),
        ),
    ]
