# Generated by Django 3.2.6 on 2021-08-14 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0006_alter_courseinfo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raceinfo',
            name='course',
        ),
        migrations.RemoveField(
            model_name='raceinfo',
            name='date',
        ),
        migrations.RemoveField(
            model_name='raceinfo',
            name='round',
        ),
    ]
