# Generated by Django 3.2.6 on 2021-08-14 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0007_auto_20210815_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceinfo',
            name='name',
            field=models.CharField(default='race', max_length=64),
        ),
    ]
